// frontend/src/views/ClientesView.vue
<template>
  <div class="page-container">
    <div class="header-actions" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
      <h1 class="page-title" style="margin-bottom: 0;">Gestión de Clientes</h1>
      <button class="btn-primary" @click="openModal()">+ Nuevo Cliente</button>
    </div>
    
    <div class="glass-panel" style="overflow-x: auto;">
      <table class="data-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre Completo</th>
            <th>Correo Electrónico</th>
            <th>Teléfono</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="cliente in clientes" :key="cliente.id_cliente">
            <td>{{ cliente.id_cliente }}</td>
            <td>{{ cliente.nombre_completo }}</td>
            <td>{{ cliente.correo }}</td>
            <td>{{ cliente.telefono || 'N/A' }}</td>
            <td>
              <button class="btn-icon" title="Editar" @click="editCliente(cliente.id_cliente)">✏️</button>
              <button class="btn-icon text-danger" title="Eliminar" @click="deleteCliente(cliente.id_cliente)">🗑️</button>
            </td>
          </tr>
          <tr v-if="clientes.length === 0">
            <td colspan="5" style="text-align: center; padding: 2rem; color: var(--text-secondary)">
              No hay clientes registrados o cargando...
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Modal Formulario -->
    <div v-if="showModal" class="modal-overlay" @click.self="closeModal">
      <div class="modal-content glass-panel">
        <h2 style="margin-bottom: 1.5rem;">{{ isEditing ? 'Editar' : 'Nuevo' }} Cliente</h2>
        
        <form @submit.prevent="saveCliente" class="form-grid">
          <div class="form-group">
            <label>Nombre Completo</label>
            <input v-model="form.nombre_completo" type="text" required class="form-control" placeholder="Ej: Juan Pérez" />
          </div>
          
          <div class="form-group">
            <label>Correo Electrónico</label>
            <input v-model="form.correo" type="email" required class="form-control" placeholder="Ej: juan@ejemplo.com" />
          </div>
          
          <div class="form-group">
            <label>Teléfono (Opcional)</label>
            <input v-model="form.telefono" type="text" class="form-control" placeholder="Ej: +123456789" />
          </div>
          
          <div class="form-actions">
            <button type="button" class="btn-secondary" @click="closeModal">Cancelar</button>
            <button type="submit" class="btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const clientes = ref([])

const showModal = ref(false)
const isEditing = ref(false)
const currentId = ref(null)

const form = ref({
  nombre_completo: '',
  correo: '',
  telefono: ''
})

const fetchClientes = async () => {
  try {
    const res = await fetch('/api/clientes')
    if (res.ok) {
      clientes.value = await res.json()
    }
  } catch (error) {
    console.error('Error fetching clients:', error)
  }
}

const openModal = () => {
  isEditing.value = false
  currentId.value = null
  form.value = { nombre_completo: '', correo: '', telefono: '' }
  showModal.value = true
}

const closeModal = () => {
  showModal.value = false
}

const editCliente = async (id) => {
  try {
    const res = await fetch(`/api/clientes/${id}`)
    if (res.ok) {
      const data = await res.json()
      isEditing.value = true
      currentId.value = data.id_cliente
      form.value = {
        nombre_completo: data.nombre_completo,
        correo: data.correo,
        telefono: data.telefono || ''
      }
      showModal.value = true
    } else {
      const err = await res.json()
      alert('Error: ' + err.message)
    }
  } catch (error) {
    console.error('Error fetching client details:', error)
  }
}

const saveCliente = async () => {
  try {
    const url = isEditing.value ? `/api/clientes/${currentId.value}` : '/api/clientes'
    const method = isEditing.value ? 'PUT' : 'POST'
    
    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form.value)
    })
    
    if (res.ok) {
      await fetchClientes()
      closeModal()
    } else {
      const err = await res.json()
      alert('Error: ' + err.message)
    }
  } catch (error) {
    console.error('Error saving client:', error)
  }
}

const deleteCliente = async (id) => {
  if (!confirm('¿Estás seguro de eliminar este cliente?')) return
  try {
    const res = await fetch(`/api/clientes/${id}`, { method: 'DELETE' })
    if (res.ok) {
      await fetchClientes()
    } else {
      const err = await res.json()
      alert('Error: ' + err.message)
    }
  } catch (error) {
    console.error('Error deleting client:', error)
  }
}

onMounted(() => {
  fetchClientes()
})
</script>

<style scoped>
.data-table {
  width: 100%;
  border-collapse: collapse;
}
.data-table th, .data-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--border-color);
}
.data-table th {
  font-weight: 600;
  color: var(--text-secondary);
  background: rgba(0,0,0,0.2);
}
.data-table tbody tr:hover {
  background: rgba(255,255,255,0.05);
}
.btn-icon {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.2rem;
  margin-right: 0.5rem;
  opacity: 0.8;
  transition: opacity 0.2s;
}
.btn-icon:hover {
  opacity: 1;
  transform: scale(1.1);
}

/* Modal styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0,0,0,0.6);
  backdrop-filter: blur(4px);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}
.modal-content {
  width: 100%;
  max-width: 500px;
  padding: 2rem;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);
  animation: modal-in 0.3s ease-out;
}
@keyframes modal-in {
  from { opacity: 0; transform: translateY(-20px) scale(0.95); }
  to { opacity: 1; transform: translateY(0) scale(1); }
}

.form-grid {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}
.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
.form-group label {
  font-size: 0.9rem;
  color: var(--text-secondary);
  font-weight: 500;
}
.form-control {
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid var(--border-color);
  color: var(--text-primary);
  padding: 0.75rem;
  border-radius: 8px;
  font-family: inherit;
  font-size: 1rem;
}
.form-control:focus {
  outline: none;
  border-color: var(--accent-primary);
  box-shadow: 0 0 0 2px var(--accent-glow);
}
.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;
  margin-top: 1rem;
}
.btn-secondary {
  background: rgba(255, 255, 255, 0.1);
  color: white;
  border: 1px solid var(--border-color);
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
}
.btn-secondary:hover {
  background: rgba(255, 255, 255, 0.2);
}
</style>

// frontend/src/views/ClientesView.jsx
import { useState, useEffect, useCallback, useMemo } from 'react'
import { useAuth } from '../context/AuthContext.jsx'

// helpers
const EMPTY_FORM = { nombre_completo: '', correo: '', telefono: '' }

function validate(form) {
  const errors = {}
  if (!form.nombre_completo.trim()) errors.nombre_completo = 'El nombre es requerido'
  if (!form.correo.trim()) errors.correo = 'El correo es requerido'
  else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.correo))
    errors.correo = 'Formato de correo inválido'
  return errors
}

// Modal formulario
function ClienteModal({ item, onSave, onClose }) {
  const isEdit = Boolean(item?.id_cliente)
  const [form, setForm] = useState(
    isEdit
      ? { nombre_completo: item.nombre_completo, correo: item.correo, telefono: item.telefono ?? '' }
      : EMPTY_FORM
  )
  const [errors, setErrors] = useState({})
  const [saving, setSaving] = useState(false)

  const handleChange = (e) => {
    const { name, value } = e.target
    setForm(f => ({ ...f, [name]: value }))
    if (errors[name]) setErrors(e => ({ ...e, [name]: undefined }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    const errs = validate(form)
    if (Object.keys(errs).length) { setErrors(errs); return }
    setSaving(true)
    await onSave(form)
    setSaving(false)
  }

  // Render del modal
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h2 className="modal-title">{isEdit ? 'Editar Cliente' : 'Nuevo Cliente'}</h2>
          <button className="btn-close" onClick={onClose}>✕</button>
        </div>
        <form onSubmit={handleSubmit} noValidate>
          <div className="modal-body">
            <div className="form-group">
              <label className="form-label" htmlFor="cli-nombre">Nombre completo *</label>
              <input
                id="cli-nombre"
                name="nombre_completo"
                autoFocus
                className={`form-control ${errors.nombre_completo ? 'error' : ''}`}
                placeholder="Ej: Juan Pérez García"
                value={form.nombre_completo}
                onChange={handleChange}
              />
              {errors.nombre_completo && <span className="form-error">{errors.nombre_completo}</span>}
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="cli-correo">Correo *</label>
              <input
                id="cli-correo"
                name="correo"
                type="email"
                className={`form-control ${errors.correo ? 'error' : ''}`}
                placeholder="correo@ejemplo.com"
                value={form.correo}
                onChange={handleChange}
              />
              {errors.correo && <span className="form-error">{errors.correo}</span>}
            </div>

            <div className="form-group">
              <label className="form-label" htmlFor="cli-tel">Teléfono</label>
              <input
                id="cli-tel"
                name="telefono"
                type="tel"
                className="form-control"
                placeholder="Ej: 5555-1234"
                value={form.telefono}
                onChange={handleChange}
              />
            </div>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose} disabled={saving}>
              Cancelar
            </button>
            <button id="btn-cli-save" type="submit" className="btn btn-primary" disabled={saving}>
              {saving ? 'Guardando…' : isEdit ? 'Guardar cambios' : 'Crear cliente'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// Vista principal
export default function ClientesView() {
  const { token } = useAuth()

  const [clientes, setClientes] = useState([])
  const [loading, setLoading] = useState(true)
  const [alert, setAlert] = useState(null)
  const [search, setSearch] = useState('')
  const [modalItem, setModalItem] = useState(undefined)
  const [deleting, setDeleting] = useState(null)

  const authHeaders = useCallback(() => ({
    'Content-Type': 'application/json',
    Authorization: `Bearer ${token}`,
  }), [token])

  const showAlert = useCallback((type, msg) => {
    setAlert({ type, msg })
    setTimeout(() => setAlert(null), 4000)
  }, [])

  const fetchClientes = useCallback(async () => {
    try {
      const res = await fetch('/api/clientes', { headers: authHeaders() })
      if (!res.ok) throw new Error('Error al cargar clientes')
      setClientes(await res.json())
    } catch (err) {
      showAlert('error', err.message)
    }
  }, [authHeaders, showAlert])

  useEffect(() => {
    const init = async () => {
      setLoading(true)
      await fetchClientes()
      setLoading(false)
    }
    init()
  }, [fetchClientes])

  const clientesFiltrados = useMemo(() => {
    const q = search.toLowerCase().trim()
    if (!q) return clientes
    return clientes.filter(c =>
      c.nombre_completo?.toLowerCase().includes(q) ||
      c.correo?.toLowerCase().includes(q) ||
      c.telefono?.toLowerCase().includes(q)
    )
  }, [clientes, search])

  const handleSave = useCallback(async (form) => {
    const isEdit = Boolean(modalItem?.id_cliente)
    const url = isEdit ? `/api/clientes/${modalItem.id_cliente}` : '/api/clientes'
    const method = isEdit ? 'PUT' : 'POST'
    try {
      const res = await fetch(url, {
        method,
        headers: authHeaders(),
        body: JSON.stringify({
          nombre_completo: form.nombre_completo.trim(),
          correo: form.correo.trim(),
          telefono: form.telefono?.trim() || null,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.message || 'Error al guardar')
      showAlert('success', isEdit ? 'Cliente actualizado' : 'Cliente creado correctamente')
      setModalItem(undefined)
      await fetchClientes()
    } catch (err) {
      showAlert('error', err.message)
    }
  }, [modalItem, authHeaders, showAlert, fetchClientes])

  const handleDelete = useCallback(async (id) => {
    if (!window.confirm('¿Eliminar este cliente?')) return
    setDeleting(id)
    try {
      const res = await fetch(`/api/clientes/${id}`, {
        method: 'DELETE',
        headers: authHeaders(),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.message || 'No se pudo eliminar')
      showAlert('success', 'Cliente eliminado correctamente')
      setClientes(prev => prev.filter(c => c.id_cliente !== id))
    } catch (err) {
      showAlert('error', err.message)
    } finally {
      setDeleting(null)
    }
  }, [authHeaders, showAlert])

  return (
    <div>
      <h1 className="page-title">Clientes</h1>
      <p className="page-subtitle">Directorio de clientes — {clientesFiltrados.length} registro(s)</p>

      {alert && (
        <div className={`alert alert-${alert.type}`} role="alert">
          {alert.type === 'success' ? '✅' : '⚠️'} {alert.msg}
        </div>
      )}

      <div className="toolbar">
        <div className="search-wrapper">
          <span className="search-icon">🔍</span>
          <input
            id="cli-search"
            type="search"
            className="search-input"
            placeholder="Buscar por nombre, correo o teléfono…"
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
        <button id="btn-cli-nuevo" className="btn btn-primary" onClick={() => setModalItem(null)}>
          + Nuevo cliente
        </button>
      </div>

      <div className="card" style={{ padding: 0 }}>
        {loading ? (
          <div className="loading-state"><div className="spinner" /><span>Cargando clientes…</span></div>
        ) : clientesFiltrados.length === 0 ? (
          <div className="empty-state">
            <span style={{ fontSize: '2.5rem' }}>👥</span>
            <p>{search ? 'Sin resultados.' : 'No hay clientes registrados.'}</p>
          </div>
        ) : (
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Nombre</th>
                  <th>Correo</th>
                  <th>Teléfono</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {clientesFiltrados.map(c => (
                  <tr key={c.id_cliente}>
                    <td style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{c.id_cliente}</td>
                    <td style={{ fontWeight: 600 }}>{c.nombre_completo}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.correo}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.telefono ?? '—'}</td>
                    <td>
                      <div className="td-actions">
                        <button className="btn btn-secondary btn-sm" onClick={() => setModalItem(c)}>
                          Editar
                        </button>
                        <button
                          className="btn btn-danger btn-sm"
                          disabled={deleting === c.id_cliente}
                          onClick={() => handleDelete(c.id_cliente)}
                        >
                          {deleting === c.id_cliente ? '…' : '🗑️'}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {modalItem !== undefined && (
        <ClienteModal
          item={modalItem}
          onSave={handleSave}
          onClose={() => setModalItem(undefined)}
        />
      )}
    </div>
  )
}
