// frontend/src/views/LoginView.vue
<template>
  <div class="login-container">
    <div class="glass-panel login-box">
      <div class="login-header">
        <h2>Gestion Tienda</h2>
        <p class="text-secondary">Inicia sesión en tu cuenta</p>
      </div>

      <form @submit.prevent="handleLogin" class="form-grid">
        <div class="form-group">
          <label>Usuario</label>
          <input v-model="username" type="text" required class="form-control" placeholder="Ej: admin" />
        </div>
        
        <div class="form-group">
          <label>Contraseña</label>
          <input v-model="password" type="password" required class="form-control" placeholder="••••••••" />
        </div>

        <div v-if="errorMsg" class="error-msg">
          {{ errorMsg }}
        </div>

        <button type="submit" class="btn-primary" style="margin-top: 1rem; width: 100%;" :disabled="isLoading">
          {{ isLoading ? 'Autenticando...' : 'Entrar' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const username = ref('')
const password = ref('')
const errorMsg = ref('')
const isLoading = ref(false)

const router = useRouter()
const authStore = useAuthStore()

const handleLogin = async () => {
  errorMsg.value = ''
  isLoading.value = true

  try {
    const res = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: username.value, password: password.value })
    })

    const data = await res.json()

    if (res.ok) {
      authStore.setSession(data.token, data.user)
      router.push('/')
    } else {
      errorMsg.value = data.message || 'Credenciales inválidas'
    }
  } catch (error) {
    console.error('Error in login:', error)
    errorMsg.value = 'Error conectando con el servidor'
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 1rem;
}

.login-box {
  width: 100%;
  max-width: 400px;
  padding: 2.5rem;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
}

.login-header {
  text-align: center;
  margin-bottom: 2rem;
}


.login-header h2 {
  font-weight: 700;
  font-size: 1.75rem;
  margin-bottom: 0.25rem;
}

.form-grid {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-group label {
  font-size: 0.9rem;
  color: var(--text-secondary);
  font-weight: 500;
}

.form-control {
  background: #f8f5f0;
  border: 1px solid var(--border-color);
  color: var(--text-primary);
  padding: 0.75rem;
  border-radius: 8px;
  font-family: inherit;
  font-size: 1rem;
  transition: all 0.3s ease;
}

.form-control:focus {
  outline: none;
  border-color: var(--accent-primary);
  box-shadow: 0 0 0 2px var(--accent-glow);
  background: #fff;
}

.error-msg {
  color: #991b1b;
  background: rgba(239, 68, 68, 0.1);
  padding: 0.75rem;
  border-radius: 8px;
  font-size: 0.9rem;
  text-align: center;
  border: 1px solid rgba(239, 68, 68, 0.3);
}
</style>

// frontend/src/views/LoginView.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import styles from './LoginView.module.css'

export default function LoginView() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [errorMsg, setErrorMsg] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    setErrorMsg('')
    setIsLoading(true)

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      })
      const data = await res.json()

      if (res.ok) {
        // Temporal — en PASO 2 esto irá al AuthContext
        localStorage.setItem('token', data.token)
        localStorage.setItem('user', JSON.stringify(data.user))
        navigate('/', { replace: true })
      } else {
        setErrorMsg(data.message || 'Credenciales inválidas')
      }
    } catch {
      setErrorMsg('Error conectando con el servidor')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.box}>
        {/* Header */}
        <div className={styles.header}>
          <h1 className={styles.title}>Gestión Tienda</h1>
          <p className={styles.subtitle}>Inicia sesión en tu cuenta</p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className={styles.form} noValidate>
          <div className="form-group">
            <label htmlFor="login-username" className="form-label">Usuario</label>
            <input
              id="login-username"
              type="text"
              required
              autoComplete="username"
              autoFocus
              className="form-control"
              placeholder="Ej: admin"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="login-password" className="form-label">Contraseña</label>
            <input
              id="login-password"
              type="password"
              required
              autoComplete="current-password"
              className="form-control"
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          {errorMsg && (
            <div className="alert alert-error" role="alert">
              ⚠️ {errorMsg}
            </div>
          )}

          <button
            id="btn-login-submit"
            type="submit"
            className="btn btn-primary"
            style={{ width: '100%', justifyContent: 'center', padding: '0.8rem' }}
            disabled={isLoading || !username || !password}
          >
            {isLoading ? (
              <>
                <span className={styles.btnSpinner} />
                Autenticando...
              </>
            ) : (
              'Entrar'
            )}
          </button>
        </form>

        <p className={styles.hint}>
          Usuario de prueba: <strong>admin</strong>
        </p>
      </div>
    </div>
  )
}
