// frontend/src/views/ReportesView.jsx
import { useState, useEffect, useCallback } from 'react'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell,
  PieChart, Pie, Legend,
} from 'recharts'
import { useAuth } from '../context/AuthContext.jsx'

// Paleta de colores para las gráficas
const COLORS = ['#800000', '#b30000', '#cc4400', '#d97706', '#059669', '#2563eb', '#7c3aed', '#db2777']

// Formateador largo de quetzales (tooltip y tablas)
const fmtQ = (v) => `Q${Number(v).toLocaleString('es-GT', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

// Formateador adaptativo para ejes que se ajusta a la magnitud real de los datos
const fmtAxis = (v) => {
  if (Math.abs(v) >= 1_000_000) return `Q${(v / 1_000_000).toFixed(1)}M`
  if (Math.abs(v) >= 1_000) return `Q${(v / 1_000).toFixed(0)}k`
  if (Math.abs(v) >= 1) return `Q${v.toFixed(0)}`
  return `Q${v.toFixed(2)}`
}

// Calcula el ancho necesario para el Y Axis según el valor máximo
const yAxisWidth = (maxVal) => {
  const label = fmtAxis(maxVal)
  return Math.max(55, label.length * 8)
}

// Tooltip personalizado para barras
function CustomTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  return (
    <div style={{
      background: 'var(--bg-panel)', border: '1px solid var(--border)',
      borderRadius: 'var(--radius-md)', padding: '0.75rem 1rem',
      boxShadow: 'var(--shadow-md)', minWidth: '180px'
    }}>
      <p style={{ fontWeight: 700, marginBottom: '0.4rem', color: 'var(--text-primary)' }}>{label}</p>
      {payload.map((p, i) => (
        <p key={i} style={{ color: p.color, fontSize: '0.88rem' }}>
          {p.name}: <strong>{typeof p.value === 'number' && p.name.includes('Q') ? fmtQ(p.value) : p.value}</strong>
        </p>
      ))}
    </div>
  )
}

// Sección colapsable
function ReportSection({ id, title, badge, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="card" style={{ marginBottom: '1.25rem', padding: 0, overflow: 'hidden' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '1.1rem 1.5rem', background: 'none', border: 'none',
          cursor: 'pointer', fontFamily: 'inherit', textAlign: 'left',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--text-primary)' }}>{title}</span>
          {badge && <span className="badge badge-neutral">{badge}</span>}
        </div>
        <span style={{ color: 'var(--text-muted)', fontSize: '1.1rem', transition: 'transform 0.2s', transform: open ? 'rotate(180deg)' : 'none' }}>
          ▾
        </span>
      </button>
      {open && (
        <div id={id} style={{ padding: '0 1.5rem 1.5rem', borderTop: '1px solid var(--border)' }}>
          {children}
        </div>
      )}
    </div>
  )
}

export default function ReportesView() {
  const { token } = useAuth()

  const [ventasCat, setVentasCat] = useState([])
  const [topClientes, setTopClientes] = useState([])
  const [stockBajo, setStockBajo] = useState({ promedio_stock: 0, productos: [] })
  const [clientesSin, setClientesSin] = useState([])
  const [loading, setLoading] = useState(true)
  const [alert, setAlert] = useState(null)

  const authHeaders = useCallback(() => ({
    'Content-Type': 'application/json',
    Authorization: `Bearer ${token}`,
  }), [token])

  useEffect(() => {
    const init = async () => {
      setLoading(true)
      try {
        const [vcRes, tcRes, sbRes, csRes] = await Promise.all([
          fetch('/api/reportes/ventas-por-categoria', { headers: authHeaders() }),
          fetch('/api/reportes/top-clientes', { headers: authHeaders() }),
          fetch('/api/reportes/stock-bajo', { headers: authHeaders() }),
          fetch('/api/reportes/clientes-sin-compra', { headers: authHeaders() }),
        ])
        setVentasCat(await vcRes.json())
        setTopClientes(await tcRes.json())
        setStockBajo(await sbRes.json())
        setClientesSin(await csRes.json())
      } catch {
        setAlert('Error al cargar los reportes. Revisa tu conexión.')
      } finally {
        setLoading(false)
      }
    }
    init()
  }, [authHeaders])

  if (loading) {
    return (
      <div>
        <h1 className="page-title">Reportes</h1>
        <div className="loading-state"><div className="spinner" /><span>Cargando reportes…</span></div>
      </div>
    )
  }

  // Datos procesados para la gráfica de pastel (top 5 categorías)
  const pieData = ventasCat.slice(0, 6).map((r, i) => ({
    name: r.categoria,
    value: Number(r.ingresos_totales),
    color: COLORS[i % COLORS.length],
  }))

  return (
    <div>
      <h1 className="page-title">Reportes</h1>
      <p className="page-subtitle">Análisis del negocio con datos reales de la base de datos.</p>

      {alert && (
        <div className="alert alert-error" role="alert">⚠️ {alert}</div>
      )}

      {/* KPIs rápidos */}
      <div className="stats-grid" style={{ marginBottom: '1.75rem' }}>
        <div className="stat-card">
          <div className="stat-label">Categorías con ventas</div>
          <div className="stat-value">{ventasCat.length}</div>
          <div className="stat-icon">📂</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Top clientes</div>
          <div className="stat-value">{topClientes.length}</div>
          <div className="stat-icon">🏆</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Productos stock bajo</div>
          <div className="stat-value" style={{ color: stockBajo.productos.length > 0 ? 'var(--danger)' : 'var(--success)' }}>
            {stockBajo.productos.length}
          </div>
          <div className="stat-icon">⚠️</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Clientes sin compras</div>
          <div className="stat-value">{clientesSin.length}</div>
          <div className="stat-icon">👤</div>
        </div>
      </div>

      {/* Reporte 1: Ventas por categoría (barras + pastel) */}
      <ReportSection
        id="reporte-ventas-categoria"
        title="Ingresos por categoría"
        badge={`${ventasCat.length} categorías`}
        defaultOpen={true}
      >
        {ventasCat.length === 0 ? (
          <div className="empty-state"><span>📊</span><p>Sin datos de ventas aún.</p></div>
        ) : (
          <>
            {/* Gráfica de barras, ingresos */}
            <div style={{ marginTop: '1.25rem', marginBottom: '1.75rem' }}>
              <p style={{ fontWeight: 600, marginBottom: '0.75rem', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                Ingresos totales por categoría (Q)
              </p>
              {(() => {
                const maxVal = Math.max(...ventasCat.map(r => Number(r.ingresos_totales)), 1)
                const w = yAxisWidth(maxVal)
                return (
                  <ResponsiveContainer width="100%" height={300}>
                    <BarChart data={ventasCat} margin={{ top: 5, right: 20, left: w - 40, bottom: 65 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                      <XAxis
                        dataKey="categoria"
                        tick={{ fontSize: 12, fill: 'var(--text-secondary)' }}
                        angle={-35}
                        textAnchor="end"
                        interval={0}
                      />
                      <YAxis
                        width={w}
                        tickFormatter={fmtAxis}
                        tick={{ fontSize: 11, fill: 'var(--text-muted)' }}
                        domain={[0, 'auto']}
                      />
                      <Tooltip content={<CustomTooltip />} />
                      <Bar dataKey="ingresos_totales" name="Ingresos (Q)" radius={[4, 4, 0, 0]}>
                        {ventasCat.map((_, i) => (
                          <Cell key={i} fill={COLORS[i % COLORS.length]} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                )
              })()}
            </div>

            {/* Gráfica de pastel, distribución */}
            <div style={{ marginBottom: '1.25rem' }}>
              <p style={{ fontWeight: 600, marginBottom: '0.75rem', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                Distribución de ingresos (top 6)
              </p>
              <ResponsiveContainer width="100%" height={260}>
                <PieChart>
                  <Pie
                    data={pieData}
                    dataKey="value"
                    nameKey="name"
                    cx="50%"
                    cy="50%"
                    outerRadius={90}
                    label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    labelLine={false}
                  >
                    {pieData.map((entry, i) => (
                      <Cell key={i} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(v) => fmtQ(v)} />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </div>

            {/* Tabla detallada */}
            <div className="table-wrapper">
              <table>
                <thead>
                  <tr>
                    <th>Categoría</th>
                    <th>Ventas</th>
                    <th>Unidades</th>
                    <th>Precio prom.</th>
                    <th>Ingresos totales</th>
                  </tr>
                </thead>
                <tbody>
                  {ventasCat.map((r, i) => (
                    <tr key={r.categoria}>
                      <td>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}>
                          <span style={{ width: 10, height: 10, borderRadius: '50%', background: COLORS[i % COLORS.length], display: 'inline-block', flexShrink: 0 }} />
                          {r.categoria}
                        </span>
                      </td>
                      <td>{r.total_ventas}</td>
                      <td>{r.unidades_vendidas}</td>
                      <td>{fmtQ(r.precio_promedio)}</td>
                      <td style={{ fontWeight: 700, color: 'var(--accent)' }}>{fmtQ(r.ingresos_totales)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </ReportSection>

      {/* Reporte 2: Top clientes */}
      <ReportSection
        id="reporte-top-clientes"
        title="Top 10 clientes por compras"
        badge={`${topClientes.length} clientes`}
      >
        {topClientes.length === 0 ? (
          <div className="empty-state"><span>🏆</span><p>Sin datos de ventas aún.</p></div>
        ) : (
          <>
            {/* Barras horizontales */}
            <div style={{ marginTop: '1.25rem', marginBottom: '1.5rem' }}>
              <p style={{ fontWeight: 600, marginBottom: '0.75rem', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                Monto total comprado (Q)
              </p>
              {(() => {
                const maxVal = Math.max(...topClientes.map(c => Number(c.monto_total)), 1)
                return (
                  <ResponsiveContainer width="100%" height={Math.max(220, topClientes.length * 38)}>
                    <BarChart
                      data={topClientes}
                      layout="vertical"
                      margin={{ top: 0, right: 90, left: 10, bottom: 0 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" horizontal={false} />
                      <XAxis
                        type="number"
                        tickFormatter={fmtAxis}
                        tick={{ fontSize: 11, fill: 'var(--text-muted)' }}
                        domain={[0, maxVal * 1.1]}
                      />
                      <YAxis
                        type="category"
                        dataKey="nombre_completo"
                        width={140}
                        tick={{ fontSize: 11, fill: 'var(--text-secondary)' }}
                      />
                      <Tooltip content={<CustomTooltip />} />
                      <Bar dataKey="monto_total" name="Total (Q)" radius={[0, 4, 4, 0]}>
                        {topClientes.map((_, i) => (
                          <Cell key={i} fill={COLORS[i % COLORS.length]} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                )
              })()}
            </div>

            <div className="table-wrapper">
              <table>
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Cliente</th>
                    <th>Correo</th>
                    <th>Compras</th>
                    <th>Última compra</th>
                    <th>Monto total</th>
                  </tr>
                </thead>
                <tbody>
                  {topClientes.map(c => (
                    <tr key={c.nombre_completo}>
                      <td>
                        <span className={`badge ${Number(c.posicion) <= 3 ? 'badge-warning' : 'badge-neutral'}`}>
                          #{c.posicion}
                        </span>
                      </td>
                      <td style={{ fontWeight: 600 }}>{c.nombre_completo}</td>
                      <td style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{c.correo}</td>
                      <td>{c.cantidad_compras}</td>
                      <td style={{ fontSize: '0.85rem' }}>
                        {new Date(c.ultima_compra).toLocaleDateString('es-GT')}
                      </td>
                      <td style={{ fontWeight: 700, color: 'var(--accent)' }}>{fmtQ(c.monto_total)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </ReportSection>

      {/* Reporte 3: Stock bajo */}
      <ReportSection
        id="reporte-stock-bajo"
        title="Productos con stock bajo"
        badge={`Promedio: ${stockBajo.promedio_stock} unidades`}
      >
        {stockBajo.productos.length === 0 ? (
          <div className="empty-state" style={{ marginTop: '1rem' }}>
            <span style={{ fontSize: '2rem' }}>✅</span>
            <p>Todos los productos tienen stock saludable.</p>
          </div>
        ) : (
          <div className="table-wrapper" style={{ marginTop: '1rem' }}>
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Producto</th>
                  <th>Categoría</th>
                  <th>Precio</th>
                  <th>Stock actual</th>
                  <th>Estado</th>
                </tr>
              </thead>
              <tbody>
                {stockBajo.productos.map(p => (
                  <tr key={p.id_producto}>
                    <td style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{p.id_producto}</td>
                    <td style={{ fontWeight: 600 }}>{p.nombre}</td>
                    <td><span className="badge badge-neutral">{p.categoria}</span></td>
                    <td>{fmtQ(p.precio_actual)}</td>
                    <td>
                      <span className={`badge ${p.stock === 0 ? 'badge-danger' : 'badge-warning'}`}>
                        {p.stock} uds.
                      </span>
                    </td>
                    <td style={{ fontSize: '0.85rem', color: p.stock === 0 ? 'var(--danger)' : 'var(--warning)' }}>
                      {p.stock === 0 ? '🔴 Sin stock' : '🟡 Stock bajo'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </ReportSection>

      {/* Reporte 4: Clientes sin compras */}
      <ReportSection
        id="reporte-clientes-sin-compra"
        title="Clientes sin compras registradas"
        badge={`${clientesSin.length} clientes`}
      >
        {clientesSin.length === 0 ? (
          <div className="empty-state" style={{ marginTop: '1rem' }}>
            <span style={{ fontSize: '2rem' }}>🎉</span>
            <p>¡Todos los clientes han realizado al menos una compra!</p>
          </div>
        ) : (
          <div className="table-wrapper" style={{ marginTop: '1rem' }}>
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Nombre</th>
                  <th>Correo</th>
                  <th>Teléfono</th>
                </tr>
              </thead>
              <tbody>
                {clientesSin.map(c => (
                  <tr key={c.id_cliente}>
                    <td style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{c.id_cliente}</td>
                    <td style={{ fontWeight: 600 }}>{c.nombre_completo}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.correo}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.telefono ?? '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </ReportSection>
    </div>
  )
}

// frontend/src/views/ReportesView.vue
<template>
  <div class="page-container">
    <div class="header-actions" style="margin-bottom: 2rem;">
      <h1 class="page-title" style="margin-bottom: 0;">Reportes Avanzados</h1>
      <p class="text-secondary" style="margin-top: 0.5rem;">
        Consultas complejas con agrupaciones, subconsultas y CTEs.
      </p>
    </div>
    
    <div class="glass-panel" style="padding: 1rem; margin-bottom: 2rem;">
      <div class="tabs">
        <button 
          v-for="tab in tabs" 
          :key="tab.id"
          :class="['tab-btn', { active: activeTab === tab.id }]"
          @click="selectTab(tab.id)"
        >
          {{ tab.name }}
        </button>
      </div>
    </div>

    <div class="glass-panel p-6" style="overflow-x: auto; min-height: 300px;">
      
      <!-- Cargando -->
      <div v-if="isLoading" style="text-align: center; padding: 3rem 0; color: var(--text-secondary)">
        Cargando reporte...
      </div>

      <!-- Reporte 1: Ventas por Categoría -->
      <div v-else-if="activeTab === 'ventas_categoria'">
        <h3 style="margin-bottom: 1rem; color: var(--accent-primary)">Ingresos y ventas por categoría</h3>
        <table class="data-table">
          <thead>
            <tr>
              <th>Categoría</th>
              <th>Ventas (Transacciones)</th>
              <th>Unidades Vendidas</th>
              <th>Ingresos Totales</th>
              <th>Precio Promedio</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in reportData.ventas_categoria" :key="item.categoria">
              <td>{{ item.categoria }}</td>
              <td>{{ item.total_ventas }}</td>
              <td>{{ item.unidades_vendidas }}</td>
              <td style="color: var(--success); font-weight: bold;">${{ Number(item.ingresos_totales).toFixed(2) }}</td>
              <td>${{ Number(item.precio_promedio).toFixed(2) }}</td>
            </tr>
            <tr v-if="reportData.ventas_categoria.length === 0">
              <td colspan="5" style="text-align: center; padding: 1rem;">No hay datos para mostrar.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Reporte 2: Stock Bajo -->
      <div v-else-if="activeTab === 'stock_bajo'">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
          <h3 style="color: var(--accent-primary)">Productos con stock por debajo del promedio</h3>
          <span class="badge-warning" v-if="reportData.stock_bajo_promedio">
            Promedio global: {{ reportData.stock_bajo_promedio }}
          </span>
        </div>
        <table class="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Producto</th>
              <th>Categoría</th>
              <th>Precio</th>
              <th>Stock Actual</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in reportData.stock_bajo" :key="item.id_producto">
              <td>{{ item.id_producto }}</td>
              <td>{{ item.nombre }}</td>
              <td>{{ item.categoria }}</td>
              <td>${{ Number(item.precio_actual).toFixed(2) }}</td>
              <td style="color: var(--danger); font-weight: bold;">{{ item.stock }}</td>
            </tr>
            <tr v-if="reportData.stock_bajo.length === 0">
              <td colspan="5" style="text-align: center; padding: 1rem;">Todos los productos están sobre el promedio.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Reporte 3: Top Clientes -->
      <div v-else-if="activeTab === 'top_clientes'">
        <h3 style="margin-bottom: 1rem; color: var(--accent-primary)">Ranking de Mejores Clientes</h3>
        <table class="data-table">
          <thead>
            <tr>
              <th>Rank</th>
              <th>Cliente</th>
              <th>Correo</th>
              <th>Cant. Compras</th>
              <th>Última Compra</th>
              <th>Monto Total</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in reportData.top_clientes" :key="item.posicion">
              <td><span class="rank-badge">{{ item.posicion }}</span></td>
              <td>{{ item.nombre_completo }}</td>
              <td>{{ item.correo }}</td>
              <td>{{ item.cantidad_compras }}</td>
              <td>{{ new Date(item.ultima_compra).toLocaleDateString() }}</td>
              <td style="color: var(--success); font-weight: bold;">${{ Number(item.monto_total).toFixed(2) }}</td>
            </tr>
            <tr v-if="reportData.top_clientes.length === 0">
              <td colspan="6" style="text-align: center; padding: 1rem;">No hay clientes con compras.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Reporte 4: Clientes sin compras -->
      <div v-else-if="activeTab === 'clientes_sin_compra'">
        <h3 style="margin-bottom: 1rem; color: var(--accent-primary)">Clientes que nunca han comprado</h3>
        <table class="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre Completo</th>
              <th>Correo Electrónico</th>
              <th>Teléfono</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in reportData.clientes_sin_compra" :key="item.id_cliente">
              <td>{{ item.id_cliente }}</td>
              <td>{{ item.nombre_completo }}</td>
              <td>{{ item.correo }}</td>
              <td>{{ item.telefono || 'N/A' }}</td>
            </tr>
            <tr v-if="reportData.clientes_sin_compra.length === 0">
              <td colspan="4" style="text-align: center; padding: 1rem;">Todos los clientes han comprado al menos una vez.</td>
            </tr>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const tabs = [
  { id: 'ventas_categoria', name: 'Ventas por Categoría' },
  { id: 'stock_bajo', name: 'Stock Bajo Promedio' },
  { id: 'top_clientes', name: 'Ranking Clientes' },
  { id: 'clientes_sin_compra', name: 'Clientes Sin Compras' }
]

const activeTab = ref('ventas_categoria')
const isLoading = ref(false)

const reportData = ref({
  ventas_categoria: [],
  stock_bajo: [],
  stock_bajo_promedio: null,
  top_clientes: [],
  clientes_sin_compra: []
})

const fetchReport = async (tabId) => {
  isLoading.value = true
  try {
    if (tabId === 'ventas_categoria') {
      const res = await fetch('/api/reportes/ventas-por-categoria')
      reportData.value.ventas_categoria = await res.json()
    } 
    else if (tabId === 'stock_bajo') {
      const res = await fetch('/api/reportes/stock-bajo')
      const data = await res.json()
      reportData.value.stock_bajo = data.productos || []
      reportData.value.stock_bajo_promedio = data.promedio_stock
    }
    else if (tabId === 'top_clientes') {
      const res = await fetch('/api/reportes/top-clientes')
      reportData.value.top_clientes = await res.json()
    }
    else if (tabId === 'clientes_sin_compra') {
      const res = await fetch('/api/reportes/clientes-sin-compra')
      reportData.value.clientes_sin_compra = await res.json()
    }
  } catch (err) {
    console.error('Error fetching report:', err)
  } finally {
    isLoading.value = false
  }
}

const selectTab = (tabId) => {
  activeTab.value = tabId
  fetchReport(tabId)
}

onMounted(() => {
  fetchReport(activeTab.value)
})
</script>

<style scoped>
.tabs {
  display: flex;
  gap: 0.5rem;
  overflow-x: auto;
  padding-bottom: 0.5rem;
}
.tab-btn {
  background: rgba(255, 255, 255, 0.05);
  color: var(--text-secondary);
  border: 1px solid var(--border-color);
  padding: 0.75rem 1.25rem;
  border-radius: 8px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
  white-space: nowrap;
}
.tab-btn:hover {
  background: rgba(255, 255, 255, 0.1);
  color: var(--text-primary);
}
.tab-btn.active {
  background: var(--accent-primary);
  color: white;
  border-color: var(--accent-primary);
  box-shadow: 0 4px 12px var(--accent-glow);
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}
.data-table th, .data-table td {
  padding: 1rem;
  text-align: left;
  border-bottom: 1px solid var(--border-color);
}
.data-table th {
  font-weight: 600;
  color: var(--text-secondary);
  background: rgba(0,0,0,0.2);
}
.data-table tbody tr:hover {
  background: rgba(255,255,255,0.05);
}

.badge-warning {
  background: rgba(245, 158, 11, 0.2);
  color: #fcd34d;
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.9rem;
  font-weight: 600;
  border: 1px solid rgba(245, 158, 11, 0.3);
}

.rank-badge {
  background: linear-gradient(135deg, #fbbf24, #d97706);
  color: #fff;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-weight: bold;
  font-size: 0.9rem;
  box-shadow: 0 2px 5px rgba(0,0,0,0.3);
}
</style>
